# Generated by Django 4.1.7 on 2023-03-16 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoinData",
            fields=[
                ("row_id", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.CharField(blank=True, max_length=5000, null=True)),
                ("symbol", models.CharField(blank=True, max_length=5000, null=True)),
                ("name", models.CharField(blank=True, max_length=5000, null=True)),
                ("image", models.CharField(blank=True, max_length=5000, null=True)),
                ("current_price", models.FloatField(blank=True, null=True)),
                ("market_cap", models.FloatField(blank=True, null=True)),
                ("market_cap_rank", models.FloatField(blank=True, null=True)),
                ("fully_diluted_valuation", models.FloatField(blank=True, null=True)),
                ("total_volume", models.FloatField(blank=True, null=True)),
                ("high_24h", models.FloatField(blank=True, null=True)),
                ("low_24h", models.FloatField(blank=True, null=True)),
                ("price_change_24h", models.FloatField(blank=True, null=True)),
                (
                    "price_change_percentage_24h",
                    models.FloatField(blank=True, null=True),
                ),
                ("market_cap_change_24h", models.FloatField(blank=True, null=True)),
                (
                    "market_cap_change_percentage_24h",
                    models.FloatField(blank=True, null=True),
                ),
                ("circulating_supply", models.FloatField(blank=True, null=True)),
                ("total_supply", models.FloatField(blank=True, null=True)),
                ("max_supply", models.FloatField(blank=True, null=True)),
                ("ath", models.FloatField(blank=True, null=True)),
                ("ath_change_percentage", models.FloatField(blank=True, null=True)),
                ("ath_date", models.CharField(blank=True, max_length=5000, null=True)),
                ("atl", models.FloatField(blank=True, null=True)),
                ("atl_change_percentage", models.FloatField(blank=True, null=True)),
                ("atl_date", models.CharField(blank=True, max_length=5000, null=True)),
                ("times", models.FloatField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=5000, null=True)),
                ("percentage", models.FloatField(blank=True, null=True)),
                (
                    "last_updated",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "coin_data",
            },
        ),
    ]
